package jp.co.stnet.cms.domain.common.message;
/**
 * Message Id
 */
public class MessageKeys {
    /** e.sl.fw.5001=Resource not found. */
    public static final String E_SL_FW_5001 = "e.sl.fw.5001";
    /** e.sl.fw.6001=File upload error occurred! */
    public static final String E_SL_FW_6001 = "e.sl.fw.6001";
    /** e.sl.fw.7001=Illegal screen flow detected! */
    public static final String E_SL_FW_7001 = "e.sl.fw.7001";
    /** e.sl.fw.7002=CSRF attack detected! */
    public static final String E_SL_FW_7002 = "e.sl.fw.7002";
    /** e.sl.fw.7003=Access Denied detected! */
    public static final String E_SL_FW_7003 = "e.sl.fw.7003";
    /** e.sl.fw.7004=Missing CSRF detected! */
    public static final String E_SL_FW_7004 = "e.sl.fw.7004";
    /** e.sl.fw.7005=Prohibited character detected! */
    public static final String E_SL_FW_7005 = "e.sl.fw.7005";
    /** e.sl.fw.8001=Business error occurred! */
    public static final String E_SL_FW_8001 = "e.sl.fw.8001";
    /** e.sl.fw.9001=System error occurred! */
    public static final String E_SL_FW_9001 = "e.sl.fw.9001";
    /** e.sl.fw.9002=Data Access error! */
    public static final String E_SL_FW_9002 = "e.sl.fw.9002";
    /** e.sl.pr.2001=The URL has expired. */
    public static final String E_SL_PR_2001 = "e.sl.pr.2001";
    /** e.sl.pr.5001=Given username does not match with token. */
    public static final String E_SL_PR_5001 = "e.sl.pr.5001";
    /** e.sl.pr.5002=Given token was not found. */
    public static final String E_SL_PR_5002 = "e.sl.pr.5002";
    /** e.sl.pr.5003=Invalid Secret. */
    public static final String E_SL_PR_5003 = "e.sl.pr.5003";
    /** e.sl.pr.5004=Max number of attempts was exceeded. */
    public static final String E_SL_PR_5004 = "e.sl.pr.5004";
    /** e.sl.fa.5001=Given account is not found! username : {0}. */
    public static final String E_SL_FA_5001 = "e.sl.fa.5001";
    /** e.sl.ac.5001=Given username already exists! */
    public static final String E_SL_AC_5001 = "e.sl.ac.5001";
    /** w.sl.pe.0001=Your password has expired. Please change. */
    public static final String W_SL_PE_0001 = "w.sl.pe.0001";
    /** title.welcome.home=welcome home */
    public static final String TITLE_WELCOME_HOME = "title.welcome.home";
    /** typeMismatch="{0}" is invalid. */
    public static final String TYPEMISMATCH = "typeMismatch";
    /** typeMismatch.int="{0}" must be an integer. */
    public static final String TYPEMISMATCH_INT = "typeMismatch.int";
    /** typeMismatch.double="{0}" must be a double. */
    public static final String TYPEMISMATCH_DOUBLE = "typeMismatch.double";
    /** typeMismatch.float="{0}" must be a float. */
    public static final String TYPEMISMATCH_FLOAT = "typeMismatch.float";
    /** typeMismatch.long="{0}" must be a long. */
    public static final String TYPEMISMATCH_LONG = "typeMismatch.long";
    /** typeMismatch.short="{0}" must be a short. */
    public static final String TYPEMISMATCH_SHORT = "typeMismatch.short";
    /** typeMismatch.boolean="{0}" must be a boolean. */
    public static final String TYPEMISMATCH_BOOLEAN = "typeMismatch.boolean";
    /** typeMismatch.java.lang.Integer="{0}" must be an integer. */
    public static final String TYPEMISMATCH_JAVA_LANG_INTEGER = "typeMismatch.java.lang.Integer";
    /** typeMismatch.java.lang.Double="{0}" must be a double. */
    public static final String TYPEMISMATCH_JAVA_LANG_DOUBLE = "typeMismatch.java.lang.Double";
    /** typeMismatch.java.lang.Float="{0}" must be a float. */
    public static final String TYPEMISMATCH_JAVA_LANG_FLOAT = "typeMismatch.java.lang.Float";
    /** typeMismatch.java.lang.Long="{0}" must be a long. */
    public static final String TYPEMISMATCH_JAVA_LANG_LONG = "typeMismatch.java.lang.Long";
    /** typeMismatch.java.lang.Short="{0}" must be a short. */
    public static final String TYPEMISMATCH_JAVA_LANG_SHORT = "typeMismatch.java.lang.Short";
    /** typeMismatch.java.lang.Boolean="{0}" is not a boolean. */
    public static final String TYPEMISMATCH_JAVA_LANG_BOOLEAN = "typeMismatch.java.lang.Boolean";
    /** typeMismatch.java.util.Date="{0}" is not a date. */
    public static final String TYPEMISMATCH_JAVA_UTIL_DATE = "typeMismatch.java.util.Date";
    /** typeMismatch.java.lang.Enum="{0}" is not a valid value. */
    public static final String TYPEMISMATCH_JAVA_LANG_ENUM = "typeMismatch.java.lang.Enum";
    /** i.cm.fw.0001=登録しました。 */
    public static final String I_CM_FW_0001 = "i.cm.fw.0001";
    /** i.cm.fw.0002=状態を変更しました。 */
    public static final String I_CM_FW_0002 = "i.cm.fw.0002";
    /** i.cm.fw.0003=データを削除しました。 */
    public static final String I_CM_FW_0003 = "i.cm.fw.0003";
    /** i.cm.fw.0004=保存しました。 */
    public static final String I_CM_FW_0004 = "i.cm.fw.0004";
    /** i.cm.fw.0005=下書き保存しました。 */
    public static final String I_CM_FW_0005 = "i.cm.fw.0005";
    /** i.cm.fw.0006=下書きを取り消しました。 */
    public static final String I_CM_FW_0006 = "i.cm.fw.0006";
    /** i.cm.fw.0007=削除しました。 */
    public static final String I_CM_FW_0007 = "i.cm.fw.0007";
    /** i.cm.fw.0008=無効データは編集できません。そのため参照モードで開きました。 */
    public static final String I_CM_FW_0008 = "i.cm.fw.0008";
    /** w.cm.fw.2001=登録内容に変更はありません。 */
    public static final String W_CM_FW_2001 = "w.cm.fw.2001";
    /** w.cm.fw.2002=同じ値が既に登録されています。({0} = {1}) */
    public static final String W_CM_FW_2002 = "w.cm.fw.2002";
    /** w.cm.fw.2003=データの状態が有効でなければ無効化できません。下書きの場合は取り消してから無効化してください。 */
    public static final String W_CM_FW_2003 = "w.cm.fw.2003";
    /** w.cm.fw.2004=データの状態が無効でなければ無効解除できません。 */
    public static final String W_CM_FW_2004 = "w.cm.fw.2004";
    /** w.cm.fw.2005=データの状態が下書きでなければ下書き取消はできません。 */
    public static final String W_CM_FW_2005 = "w.cm.fw.2005";
    /** e.cm.fw.8001=楽観的排他制御により登録に失敗しました。画面を開き直して登録をやり直して下さい。 */
    public static final String E_CM_FW_8001 = "e.cm.fw.8001";
    /** e.cm.fw.8002=制約違反によりテーブル更新に失敗しました。({0}) */
    public static final String E_CM_FW_8002 = "e.cm.fw.8002";
    /** e.cm.fw.9001=登録に失敗しました。({0}) */
    public static final String E_CM_FW_9001 = "e.cm.fw.9001";
}
